name: Pull Issue Manager
description: >- 
  This plugin has 2 features wrapped into it. The first should be used on an issue labeled event, in which you can define a set of labels to act upon.
  If the event is an issue being labelled, this will add your code template with info from the issue into the comments.
  The second action, if setup, is for branch pushes. If it sees a certain tag in the commit (which should exist in your code template) it will move the issue to the specified ZenHub pipeline.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: check-square
  color: gray-dark
inputs:
  codetemplate:
    description: The code to be inserted in the comment on this event. Please see the README for how to use templates.
    required: true
  progresstag:
    description: A tag to look for in the push commits - if found, the push event action will move the issue to the specified ZenHub pipeline
    required: true
    default: \#started
  zhapikey:
    description: Your ZenHub API Key
    required: true
  zhpipelinename:
    description: >-
      The ZenHub Pipeline name you want to move linked issues under during this
      action.
    required: true
